name = lava_crucible
title = Lava Crucible
display_name = Lava Crucible
description = Adds a crucible that can be used to melt down minerals over lava.
depends = default, ore_dust, volcanic_soil
optional_depends = moreores, moreblocks, technic
